language: node_js

node_js:
 - "10.15.0"

cache:
 directories:
   - node_modules

services:
 - postgresql

before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - npm run create:tables
 - npm install
 
 script:
 - npm test

after_success:
 - npm run coverage
 - npm run drop:tables
