language: node_js

node_js:
 - "10.15.0"

cache:
 directories:
   - node_modules

env:
  global:
    - CC_TEST_REPORTER_ID=d9f66c13285b3f306e8f7b60fabce6ef5a8050f248f096c6f9b6c40770ac20be   

before_script:
 - npm install
 - yarn global add nyc
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

 script:
 - npm test
 - nyc --reporter=lcov yarn run test

after_success:
 - npm run coverage
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 
  