language: node_js

node_js:
 - "10.15.0"

cache:
 directories:
   - node_modules

services:
 - postgresql

before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - npm install

 script:
 - npm test

after_success:
 - npm run coverage
  
script:
 - npm test

after_success:
 - npm run coverage
